#ifndef UTILITYAI_STDEFINITIONS_H_INCLUDED
#define UTILITYAI_STDEFINITIONS_H_INCLUDED

#define ST_RUNNING 0
#define ST_SUCCESS 1
#define ST_FAILURE -1
#define ST_SKIP -2


#define ST_INTERNAL_STATUS_UNTICKED     0
#define ST_INTERNAL_STATUS_TICKED       1
#define ST_INTERNAL_STATUS_COMPLETED    2

#endif